export default {
    "App":{
        "Home":"Home",
        "Futu":"Futu",
        "Search":"Search",
        "Screener":"Screener",
        "Gather":"Gather",
        "Event Calendar":"Event Calendar",
        "IPoscoop Calendar":"IPoscoop Calendar",
        "Book Viewer":"Book Viewer",
        "Setting":"Setting",
    },
    "Setting":{
        "Language":"Language",
        "Theme":"Theme",
        "Save":"Save",
    },
    "TimeViewer":{
        "Loading":"Loading"
    },
    "IPoscoop_Calendar":{
        "Company":"Company",
        "Symbol":"Symbol",
        "Managers":"Managers",
        "Shares":"Shares(Millions)",
        "Price Low":"Price Low",
        "Price High":"Price High",
        "Volume":"Est. $Volume",
        "Expected Date":"Expected Date",
    },
    "Event_Calendar":{
        "Pick Date":"Pick Date",
        "Time":"Time",
        "Country":"Country",
        "Event":"Event",
        "Importance":"Importance",
        "Actual":"Actual",
        "Forecast":"Forecast",
        "Previous":"Previous",
    },
    "Cboe_Book_Viewer":{
        "Please Input Symbol":"Please Input Symbol",
        "Last Update Time":"Last Update Time",
        "Size":"Size",
        "Price":"Price",
        "Buy":"Buy",
        "Sell":"Sell",
        "Shares":"Shares",
        "Skill":"Skill",
    },
    "Futu_Screener":{
        "Confirm":"Confirm",
        "Screener Parameters":"Screener Parameters",
        "Please Input Label":"Please Input Label",
        "Please Input Value":"Please Input Value",
        "StockCode":"StockCode",
        "Name":"Name",
        "Price":"Price",
        "ChangeRatio":"ChangeRatio",
        "Change":"Change",
        "Markcap":"Markcap",
        "Volume":"Volume",
    }
}