export default {
    "App":{
        "Home":"主页",
        "Futu":"富途",
        "Search":"搜索",
        "Screener":"筛选器",
        "Gather":"集合",
        "Event Calendar":"事件日历",
        "IPoscoop Calendar":"IPoscoop 日历",
        "Book Viewer":"订单簿",
        "Setting":"设置",
    },
    "Setting":{
        "Language":"语言",
        "Theme":"主题",
        "Save":"保存",
    },
    "TimeViewer":{
        "Loading":"加载"
    },
    "IPoscoop_Calendar":{
        "Company":"公司",
        "Symbol":"代码",
        "Managers":"管理者",
        "Shares":"股份(百万)",
        "Price Low":"最低价",
        "Price High":"最高价",
        "Volume":"预计交易量",
        "Expected Date":"预计日期",
    },
    "Event_Calendar":{
        "Pick Date":"选择日期",
        "Time":"时间",
        "Country":"国家",
        "Event":"事件",
        "Importance":"重要性",
        "Actual":"实际值",
        "Forecast":"预测值",
        "Previous":"先前值",
    },
    "Cboe_Book_Viewer":{
        "Please Input Symbol":"请输入符号",
        "Last Update Time":"最后更新时间",
        "Size":"大小",
        "Price":"价格",
        "Buy":"买",
        "Sell":"卖",
        "Shares":"股",
        "Skill":"手",
    },
    "Futu_Screener":{
        "Confirm":"确认",
        "Screener Parameters":"筛选器参数",
        "Please Input Label":"请输入标题",
        "Please Input Value":"请输入内容",
        "StockCode":"股票代码",
        "Name":"名字",
        "Price":"价格",
        "ChangeRatio":"涨幅度",
        "Change":"涨幅",
        "Markcap":"成交额",
        "Volume":"成交量",
    }
}