export default {
    "Welcome": "Welcome",
    "Language": "Language",
    "Theme Dark": "Dark",
    "Theme Light": "Light",
    "Home": "Home",
    "Futu": "Futu",
    "Gather": "Gather",
    "Search": "Search",
    "Message": "Message",
    "Event Calendar": "Event Calendar",
    "Last week": "Last week",
    "Next Week": "Next Week",
    "Time": "Time",
    "Country": "Country",
    "Event": "Event",
    "Importance": "Importance",
    "Actual": "Actual",
    "Forecast": "Forecast",
    "Previous": "Previous",
    "Pick Date": "Pick Date",
    "IPoscoop Calendar": "IPoscoop Calendar",
    "Company": "Company",
    "Symbol": "Symbol",
    "Managers": "Managers",
    "IPoscoop Shares": "Shares(Millions)",
    "IPoscoop Volume": "Est. $Volume",
    "Expected Date": "Expected Date",
    "Price High": "Price High",
    "Price Low": "Price Low",
    "Cboe": "Cboe",
    "Book Viewer": "Book Viewer",
    "Please Input": "Please Input",
    "Select Search Type": "Select Search Type",
    "Confirm":"Confirm"
}