export default {
    "Welcome": "欢迎",
    "Language": "语言",
    "Theme Dark": "暗黑",
    "Theme Light": "明亮",
    "Home": "主页",
    "Futu": "富途",
    "Gather": "集合",
    "Search": "搜索",
    "Message": "消息",
    "Event Calendar": "事件日历",
    "Last Week": "上一周",
    "Next Week": "下一周",
    "Time": "时间",
    "Country": "国家",
    "Event": "事件",
    "Importance": "重要性",
    "Actual": "今值",
    "Forecast": "预期",
    "Previous": "前值",
    "Pick Date": "选择日期",
    "IPoscoop Calendar": "IPoscoop 新股日历",
    "Company": "公司",
    "Symbol": "代码",
    "Managers": "管理员",
    "IPoscoop Shares": "股份(百万)",
    "IPoscoop Volume": "预计交易量",
    "Expected Date": "预计日期",
    "Price High": "最高价",
    "Price Low": "最低价",
    "Cboe": "Cboe",
    "Book Viewer": "订单簿",
    "Please Input": "请输入",
    "Select Search Type": "选择搜索类型",
    "Confirm":"确定"
}